networks:
  public:

services:
  backend:
    build: ./backend
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - 5000:5000
    networks:
      - public
  
  frontend:
    build: ./frontend
    command: yarn start
    ports:
      - 3000:3000
    networks:
      - public
    depends_on:
      - backend
